### ISSUE TITLE
Can't find "Fix Mac Path" in Package Control in ST3

### ISSUE THREAD

**Issue by hced** [int3h/SublimeFixMacPath#1]
On a pristine Sublime Text 3 with Package Control just installed, I can't find/install "Fix Mac Path". Is it just me?

**Comment by mxub** [comment]
me neither

**Comment by greneholt** [comment]
On the package manager site it is marked as only compatible with ST2.

**Comment by hced** [comment]
As a sub-question: does Sublime 3 correct this or is this plugin still needed in the same sense that it is for Sublime 2?

**Comment by martenson** [comment]
It is OS X issue, I created a soft symlink in the directory that ST3 actually sees (e.g. /usr/bin for me). It works.

http://overwatering.org/blog/2012/08/setting-path-osx-mountain-lion/

http://www.cyberciti.biz/faq/unix-creating-symbolic-link-ln-command/

**Comment by jfexyz** [comment]
I've sent a pull request to properly add it to the Package Control repo: https://github.com/wbond/package_control_channel/pull/2681

**Comment by jfexyz** [comment]
No go, still need @int3h to update the package control repo. #blerg

**Comment by gernotstarke** [comment]
does still not work in ST3 :-(

**Comment by stefanosc** [comment]
same issue, you have to manually clone the repo

**Comment by jesseleite** [comment]
@int3h, If this works in ST3... I can't find it in Package Control either, because it's tagged as ST2 only. Can you add it to Package Control for ST3 as well?

**Comment by stefanosc** [comment]
The best way to install this manually on SublimeText 3 is to add the repository manually through Package Control.
In SublimeText 3
1. cmd + shift + P (opens the command palette)
2. in the command palette type: pcar
3. Click on or select and hit enter on: "Package Control: Add Repository"
4. paste the link to this repo: https://github.com/int3h/SublimeFixMacPath
5. enter
6. cmd + shift + P (opens the command palette) 
7. in the command palette type: pci
8. "Package Control: Install Package"
9. type: fix, then find the FixMacPath and install it

Done :smile: 
Let me know how it goes

**Comment by mynameistechno** [comment]
Doesn't work in ST3 ...

**Comment by OliverJAsh** [comment]
@int3h Please can you update the Package Control repo so we can get this resolved?

**Comment by fredkingham** [comment]
+1

**Comment by mAAdhaTTah** [comment]
@mynameistechno After you add the repo, you have to install the old-fasioned way `Install Package` -> `SublimeFixMacPath`

**Comment by fishermanswharff** [comment]
@stefanosc that solution was perfect. worked like a charm. thanks!

**Comment by stefanosc** [comment]
@fishermanswharff sorry for the delay, glad it worked and actually I will update my instructions with @mAAdhaTTah useful point (although strangely enough it worked for me without needing to install it after adding the repo)

**Comment by int3h** [comment]
Fixed by d0d7d96 / release v1.1.0.

**Comment by ctf0** [comment]
it works on ST3 here without any probs ,just plz added to package control as i only found it by pure luck.
