### ISSUE TITLE
for me, your clone command did not work (access rights issue with githut)

### ISSUE THREAD

**Issue by gernotstarke** [int3h/SublimeFixMacPath#2]
instead, I used the following:

git clone https://github.com/int3h/SublimeFixMacPath.git  ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/FixMacPath

now the clone works :-)

**Comment by jesseleite** [comment]
Thank you, I had this problem too, but your clone worked.

@int3h, you should update your clone command example in README.  Also, you should add this package to Package Control for ST3 (right now it's only tagged as ST2, so it cannot be installed through Package Control for ST3)!
