### ISSUE TITLE
Fix Mac Path wrecks PATH on Windows

### ISSUE THREAD

**Issue by valrus** [int3h/SublimeFixMacPath#5]
Sublime Text is a cross-platform program and this plugin renders PATH an empty string on Windows. Probably it should check the platform and act as a no-op if it's not Mac.

**Comment by mehaase** [comment]
Also turns a Linux path into a blank string.

Extremely frustrating, because it breaks Package Control on Ubuntu. I spent HOURS trying to figure out why Package Control was broken. Turns out, it was this package instead.

**Comment by joseadrian** [comment]
I was going to install it because it was referenced on [sublime-gulp](https://github.com/NicoSantangelo/sublime-gulp) but now I just would keep doing those gulp tasks on Terminal.
